### ISSUE TITLE
Component is not registered correctly

### ISSUE THREAD

**Issue by tomas-nielsen** [IneoO/vue-multi-select#28]
when importing MultiSelect `from 'vue-multi-select'`
Vue will state that the component is registered incorrectly, and the component won't mount.

to make it work you need to import the source component 
`'vue-multi-select/src/components/vueMultiSelect/vue-multi-select'`

**Comment by IneoO** [comment]
Hi, Are you sure ?
Just tested atm and it worked for me
in the package.json you have 
```
"main": "dist/lib/vue-multi-select.min.js", 
```
file pointed when you use `'vue-multi-select'`

Btw your solution shouldn work since vue-multi-select is decomposed in 3 files
```
├── vue-multi-select.css
├── vue-multi-select.js
└── vue-multi-select.vue
```
Webpack won't know wish one he must import (the .vue or the .js)

you have to do `import MultiSelect from 'vue-multi-select/src/components/vueMultiSelect/vue-multi-select.vue` so.

**Comment by tomas-nielsen** [comment]
Yeah I'm sure I thought it was strange too.

the main looks as you mentioned.

i can import the source like you mentioned:
`import MultiSelect from 'vue-multi-select/src/components/vueMultiSelect/vue-multi-select.vue`

I can do this because vue-multi-select.vue import the html and css in the bottom of the file.

BTW I installed the package through npm, maybe I will clone the repo instead to see if that works?

**Comment by IneoO** [comment]
Could you provide a repo with ur pb ?

Juste tested on codesandbox and import work fine.

https://codesandbox.io/s/5knnoxqml4
