### ISSUE TITLE
the disabed dont work

### ISSUE THREAD

**Issue by JackZhouMine** [IneoO/vue-multi-select#54]
why does the disabled dont work？
```html
  <vue-multi-select v-model="test.defaultValues" search history-button :options="options" :filters="filters" :btn-label="btnLabel" :select-options="data" :disabled="true"></vue-multi-select>
```

[my demo](https://codepen.io/JackZhouMine/pen/XGyrRG)

**Comment by IneoO** [comment]
In your exemple, you are using 3.12.1. Disabled have been released in 3.14.1

If you don't want to use bundler, you can't use 4.0.0 atm, I will realease a WC build this we. You can use 3.16.0, but there is a breacking change with btnLabel, a function is needed instead of a string.

https://codepen.io/IneoO/pen/MdzQep
